name: Lint Code Base

on:
  push:
    branches-ignore: [main, Unknown-Dev]
  pull_request:
    branches: [main, Unknown-Dev]
jobs:
  build:
    name: Lint Code Base

    runs-on: ubuntu-latest
    steps:

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
